name: web

on:
  push:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'lib/**'
      - 'data/**'
      - 'packaging/**'
      - 'CMakeLists.txt'
      - '.github/workflows/web.yml'

jobs:
  web:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest
      env: { LANG: "C.UTF-8" }
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Build
        run: |
          mkdir build; cd build
          emcmake cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=
          ninja
          DESTDIR=../web ninja install

      - name: Save apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: principia-wasm
          path: web/
